---
name: Update release submodule

on:  # yamllint disable-line rule:truthy
  push:
    paths:
      - .github/workflows/update-release-submodule.yml
  schedule:
    - cron: "0 * * * *"
  repository_dispatch:
    types:
      - update-release-submodule

jobs:

  update-release-submodule:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: technote-space/create-pr-action@v2
        with:
          EXECUTE_COMMANDS: |
            git submodule update --remote
          COMMIT_EMAIL: 'bot@betacloud-solutions.de'
          COMMIT_MESSAGE: |
            chore: update release submodule
            Signed-off-by: Betacloud Solutions Bot <bot@betacloud-solutions.de>
          COMMIT_NAME: 'Betacloud Solutions Bot'
          ONLY_DEFAULT_BRANCH: true
          PR_BRANCH_NAME: 'update-release-submodule'
          PR_BRANCH_PREFIX: 'chore/'
          PR_TITLE: 'chore: update release submodule'
